### ISSUE TITLE
Black screen while zooming image.

### ISSUE THREAD

**Issue by shivamkapasia0** [sachudada/unsplash_flutter#1]
black screen while zooming image on homePage.

**Comment by sachudada** [comment]
Thankyou for letting  me know about the error.

I want to tell you that the issue has been solved. Their is no more black screen after zooming.

ERROR solution:-

In image_tile.dart file.
instead of Fullimage load use Regular image.


 @override
  Widget build(BuildContext context) => InkWell(
    onTap: () {
      // item onclick
      Navigator.of(context).push(
        MaterialPageRoute<Null>(
          builder: (BuildContext context) =>
          // open [ImagePage] with the given image
          ImagePage(image.getId(), image.getRegularUrl()),
        ),
      );
    },
